name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        working-directory: mobile-app/android
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Build Release AAB (unsigned)
        working-directory: mobile-app/android
        run: ./gradlew --no-daemon --stacktrace bundleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            mobile-app/android/app/build/outputs/apk/debug/*.apk

      - name: Upload Release AAB (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-unsigned
          path: |
            mobile-app/android/app/build/outputs/bundle/release/*.aab



